export const EXERCISE_LIST_CLEAR = 'EXERCISE_LIST_CLEAR';
export const EXERCISE_LIST_ERROR = 'EXERCISE_LIST_ERROR';
export const EXERCISE_LIST_LOAD = 'EXERCISE_LIST_LOAD';
export const EXERCISE_LIST_NAMES = 'EXERCISE_LIST_NAMES';
